server:
  # 端口配置
  port: 8080
spring:
  # 线程池配置
  task:
    execution:
      pool:
        max-size: 16
        core-size: 8
        keep-alive: 60s
        queue-capacity: 100
        allow-core-thread-timeout: true
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  # 数据库数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_db?useSSL=false&u-seUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        # 数据库监控用户名密码配置
        login-username: admin
        login-password: admin
  # 邮箱配置
  mail:
    host: smtp.163.com
    port: 25
    username: 15625295093@163.com
    # 这里的密码为密码授权码
    password: abc
    protocol: smtp
    default-encoding: UTF-8
    jndi-name: 个人悦读分享


# 存储配置，配置其一即可，类型需要严格匹配
oss:
  ## 存储类型, 1: 本地  2：七牛  3：网易云 4: 阿里云
  type: 1
  local:
    path: /var/blog/
    proxy: http://resource.poile.cn/
  # 网易云存储配置
  netease:
    accessKey: 2bec4d8797e64f99b967c88f
    secretKey: ca8bb777179949a4b07671
    endpoint: nos-eastchina1.126.net
    bucket: poile-img
  # 七牛云存储配置
  qiniu:
    accessKey: vBVb9KFP8grlTDqgWo-wzOj
    secretKey: G2bU07ymUqjVCx-2t
    region: huanan
    bucket: softwares
    domain: http://qiniu.poile.cn/
  # 阿里云存储配置
  ali:
    accessKeyId: LTAIaEe
    accessKeyIdSecret: bU54eGKPugUj03
    bucket: poile
    endpoint: oss-cn-shenzhen.aliyuncs.com

sms:
  # 短信类型，1：阿里，2：腾讯
  type: 1
  # 短信验证码有效时，单位为:秒
  expire: 300
  # 短信同一手机号最大发送条数
  day_max: 10
  # 阿里短信配置
  ali:
    regionId: cn-hangzhou
    accessKeyId: LTAIaEeboqn0kR
    accessKeySecret: bU54eGKPugU
    signName: 个人悦读分享
    templateCode: SMS_17694205
  # 腾讯短信配置
  tencent:
    appId: 14001859
    appKey: ea4d97cdc5d23f0741b
    templateId: 608484
    signName: 个人阅读分享网
# 邮件中的链接配置，按需求配置
mail:
  # 邮箱绑定时发送的验证链接前缀
  check: http://127.0.0.1:8080/email/verify
  # 文章详情前缀，文章评论邮件提醒的链接前缀
  article: http://127.0.0.1:8080/article/#/
  # 留言邮件提醒留言版页面链接
  message: http://127.0.0.1:8080/message

# 第三方登录
oauth:
  github:
    clientId: bded74b0f0213
    clientSecret: 904294b14bb
  gitee:
    clientId: 18348ed893d47d047a79fb0a395fe1c8c4
    clientSecret: ac72d64d7e1f365fb526bcaa8057c
    redirect_uri: https://www.poile.cn/oauth
  qq:
    appId: appid
    clientId: clientId
    clientSecret: clientSecret
    redirect_uri: https://www.poile.cn/oauth

# 开发环境，为调试方便，降低日志级别
logging:
  level:
    cn.poile.blog.mapper: DEBUG
    org.springframework.security: DEBUG

