spring:
  profiles:
    active:
      - prod
  application:
    name: blog-api
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: /var/tmp
      max-request-size: 5MB
      max-file-size: 5MB
  thymeleaf:
    suffix: .html
    cache: true
    encoding: UTF-8

# 忽略安全校验url列表，不可修改
ignore:
  list:
    - /actuator/**
    - /v2/api-docs
    - /swagger/api-docs
    - /swagger-resources/**
    - /swagger-ui.html
    - /webjars/**
    - /druid/**
    - /sms/**
    - /account/login
    - /mobile/login
    - /logout
    - /refresh_access_token
    - /user/register
    - /user/email/bind
    - /category/tree
    - /category/list
    - /tag/list
    - /article/published/page
    - /article/view/**
    - /article/pre_next/**
    - /article/archives/page
    - /article/category/statistic
    - /article/tag/statistic
    - /article/recommend/list
    - /article/interrelated/list
    - /article/count
    - /article/like/list
    - /friend/link/page
    - /friend/link/list
    - /article/comment/page
    - /article/comment/latest
    - /leave/message/page
    - /leave/message/latest

# mybatis-plus配置，不可修改
mybatis-plus:
  mapper-locations:
  - classpath:/mapper/*.xml
  type-aliases-package: cn.poile.bolg.entity
  global-config:
    db-config:
      # 配置逻辑删除，1：是，0：否
      logic-not-delete-value: 0
      logic-delete-value: 1
