spring:
  profiles:
    active:
      - dev
  application:
    name: ucs-blog
  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB
  thymeleaf:
    suffix: .html
    cache: true
    encoding: UTF-8

ignore:
  list:
    - /actuator/**
    - /v2/api-docs
    - /swagger/api-docs
    - /swagger-resources/**
    - /swagger-ui.html
    - /webjars/**
    - /druid/**
    - /sms/**
    - /account/login
    - /mobile/login
    - /refresh_access_token
    - /user/register
    - /email/bind
    - /category/tree
    - /category/list
    - /article/published/page
    - /article/view/**
    - /article/pre_next/**
    - /article/archives/page
    - /article/category/statistic
    - /article/tag/statistic
    - /article/recommend/list
    - /article/interrelated/list

mail:
  check:
    prefix: http://127.0.0.1:8080/email/verify
