server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_db?useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: 123456

oss:
  ## 存储类型, 0: 本地  1：七牛  2：网易云  3：腾讯云 4: 阿里云
  type: 1
  local:
    path: /var/blog/
    proxy: http://www.poile.cn/resource/
  netease:
    accessKey: 2bec4d8797e64f99b967c88fa
    secretKey: ca8bb777179949a4b0767108
    endpoint: nos-eastchina1.126.net
    bucket: poile-img
  qiniu:
    accessKey: vBVb9KFP8grlTDqgWo-wzOj4VULcr
    secretKey: G2bU07ymUqjVCx-2t1eM2Nodjsa2qqy
    region: huanan
    bucket: softwares
    domain: http://qiniu.poile.cn/


mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
  type-aliases-package: cn.poile.bolg.entity

logging:
  level:
    cn.poile.blog.mapper: DEBUG
    org.springframework.security: DEBUG
